#!/usr/bin/env bash
set -euo pipefail

INSTALL_DIR="${LAB_SERVER_INSTALL_DIR:-/opt/lab-server}"
ENV_FILE="${LAB_SERVER_ENV_FILE:-${INSTALL_DIR}/config/jupyterhub.env}"
PORT="${LAB_SERVER_BIND_PORT:-8000}"
BIND_URL="${LAB_SERVER_JUPYTERHUB_BIND_URL:-}"

if [[ "${EUID}" -ne 0 ]]; then
  echo "ERROR: run as root, for example: sudo bash scripts/bind-lan-http.sh" >&2
  exit 1
fi

if [[ -z "${BIND_URL}" ]]; then
  BIND_IP="${LAB_SERVER_BIND_IP:-}"
  if [[ -z "${BIND_IP}" ]]; then
    BIND_IP="$(hostname -I | tr ' ' '\n' | awk '/^[0-9]+\./ && $1 !~ /^127\./ { print; exit }')"
  fi

  if [[ -z "${BIND_IP}" ]]; then
    echo "ERROR: could not detect a non-local IPv4 address from hostname -I." >&2
    echo "Set LAB_SERVER_BIND_IP=<server-ip> and rerun." >&2
    exit 1
  fi

  BIND_URL="http://${BIND_IP}:${PORT}"
fi

echo "==> Setting JupyterHub public proxy bind URL to ${BIND_URL}"
echo "==> Updating ${ENV_FILE}"

install -d -m 0755 "$(dirname "${ENV_FILE}")"

TMP_FILE="$(mktemp)"
cleanup() {
  rm -f "${TMP_FILE}"
}
trap cleanup EXIT

if [[ -f "${ENV_FILE}" ]]; then
  cp "${ENV_FILE}" "${TMP_FILE}"
else
  {
    echo "# Local systemd environment overrides for lab-server."
    echo "# Generated by scripts/bind-lan-http.sh."
    echo
  } > "${TMP_FILE}"
fi

if grep -Eq '^#?LAB_SERVER_JUPYTERHUB_BIND_URL=' "${TMP_FILE}"; then
  sed -i "0,/^#\\?LAB_SERVER_JUPYTERHUB_BIND_URL=.*/s|^#\\?LAB_SERVER_JUPYTERHUB_BIND_URL=.*|LAB_SERVER_JUPYTERHUB_BIND_URL=${BIND_URL}|" "${TMP_FILE}"
else
  {
    echo
    echo "# Temporary LAN HTTP test. Prefer Nginx HTTPS for production."
    echo "LAB_SERVER_JUPYTERHUB_BIND_URL=${BIND_URL}"
  } >> "${TMP_FILE}"
fi

install -m 0644 "${TMP_FILE}" "${ENV_FILE}"

echo "==> Restarting JupyterHub"
systemctl daemon-reload
systemctl restart jupyterhub
systemctl status jupyterhub --no-pager

cat <<EOF

JupyterHub should now be reachable at:
  ${BIND_URL}

For production, restore localhost binding and put Nginx HTTPS in front:
  LAB_SERVER_JUPYTERHUB_BIND_URL=http://127.0.0.1:8000 sudo bash scripts/bind-lan-http.sh
EOF
